### ISSUE TITLE
Fix the testsuite

### ISSUE THREAD

**Issue by tobihan** [BRiAl/BRiAl#12]
Hi,

here is a minimal patch to fix the testsuite:
https://anonscm.debian.org/cgit/debian-science/packages/polybori.git/tree/debian/patches/fix-testsuite.patch

To see how to run the tests, see the target override_dh_auto_tests in
https://anonscm.debian.org/cgit/debian-science/packages/polybori.git/tree/debian/rules

Best,
Tobias

**Comment by tobihan** [comment]
Hi,

here is another patch that is required when running the testsuite with boost >= 1.62. The function boost::hash_combine() changed, so the hashes need to be updated:
https://anonscm.debian.org/cgit/debian-science/packages/polybori.git/tree/debian/patches/testsuite-boost-1.62.patch

**Comment by kiwifb** [comment]
I will start using this stuff in `libBRiAl` thanks for making those visible.

**Comment by kiwifb** [comment]
@tobihan  the first patch seem to be gone, do you have a copy somewhere?

**Comment by tobihan** [comment]
The patch is here:

https://anonscm.debian.org/cgit/debian-science/packages/polybori.git/tree/debian/patches/fix-testsuite.patch?id=ddcc668f79fde5472bf0259261687041647eac10

I removed it because running scons messed with the already built files. Also the patched file is not included anymore in brial 0.8.7.

**Comment by kiwifb** [comment]
Thank you for the link. Gosh I was just after that `;`, I probably could have figured it out by paying more attention. Yes, sorry about the removal. In retrospect that was a mistake. Now I will have to find a way to deal gracefully with the boost 1.62 patch.

**Comment by kiwifb** [comment]
The test suite is now in a working state again so closing.
