### ISSUE TITLE
do not hardcode python2.7 in configure.ac

### ISSUE THREAD

**Issue by fchapoton** [BRiAl/BRiAl#14]
Brial is apparently the last standard package in sage which does not allow python3 compilation.

see https://trac.sagemath.org/ticket/22582#comment:40

**Comment by kiwifb** [comment]
That is actually solved if we moved to `pyBRiAl`. In any case while `2.7` is hardcoded in `configure.ac`, it is a minimum version. Not an absolute version requirement.
