### ISSUE TITLE
self initialisation in groebner/include/polybori/groebner/CountCriterion.h

### ISSUE THREAD

**Issue by kiwifb** [BRiAl/BRiAl#28]
clang++ warnings pointed to a very interesting piece of code at https://github.com/BRiAl/BRiAl/blob/master/groebner/include/polybori/groebner/CountCriterion.h#L59

Inspecting the code, the variable `gcd_deg`certainly needs initialising but to what?

**Comment by kiwifb** [comment]
And it's been that way from the first commit...

**Comment by kiwifb** [comment]
I am guessing the right hand side should have been `gcd.deg()` could the author, @alexanderdreyer, confirm? I am actually surprised that neither clang++ or g++ complained that `gcd` was set but not used. With that in mind it would make sense for `gcd` to be used to set `gcd_deg`.

**Comment by rusydi** [comment]
My guess is that `gcd_deg` is used to store the degree of `gcd`, which should then be written as
`int gcd_deg = gcd.deg();`

**Comment by kiwifb** [comment]
So your guess is the same as mine. It makes sense and it makes the definition of `gcd` useful since I don't think it is used anywhere else. I will add it to my current branch fixing warnings.

**Comment by kiwifb** [comment]
Fixed by PR #29 (cross fingers).

**Comment by alexanderdreyer** [comment]
I only saw the notification today. Albeit late, I can verify that this is a proper fix.

**Comment by kiwifb** [comment]
Thank you Alexander. I know this is not your main job these days but it would be nice if you could confirm our hunch.

**Comment by alexanderdreyer** [comment]
I can confrm that your idea how that line was meant to be is right..

**Comment by kiwifb** [comment]
Thank you again for taking the time.
