### ISSUE TITLE
libbrial/include/polybori/config.h.in is missing from the master branch

### ISSUE THREAD

**Issue by kiwifb** [BRiAl/BRiAl#3]
And conversely `libpolybori/include/polybori/config.h.in` is missing from the 0.8.4.x branch.
And of course it is present in the tarball and therefore probably the tag. I found out when `automake` complained about not finding it.

**Comment by ohanar** [comment]
I'm using `autoreconf --install` and have no issues with a freshly cloned copy (either master or 0.8.4.x), which is as it should be (`config.h.in` should be autogenerated, and not in the repository).

**Comment by kiwifb** [comment]
OK I officially do it wrong.
