### ISSUE TITLE
OSX build does not pass tests

### ISSUE THREAD

**Issue by saraedum** [BRiAl/BRiAl#31]
Trying to package BRiAl for conda, we have some failing tests on OSX. Any clues on what is going on here would be very welcome https://github.com/conda-forge/brial-feedstock/pull/5 :)

**Comment by saraedum** [comment]
Seems to be a known issue: #25

**Comment by kiwifb** [comment]
Oh cool, I was wondering what the problem was.

**Comment by kiwifb** [comment]
Should be fixed in 1.2.2.
