### ISSUE TITLE
Just a thank you

### ISSUE THREAD

**Issue by msoos** [BRiAl/BRiAl#34]
Hi All,

Just a thank you for all of the developers who are maintaining this: thanks a ton. A lot of interesting work is still coming out of PolyBori/BRiAl, so it's incredibly important to maintain it. Thanks so much for your efforts!

Mate

**Comment by kiwifb** [comment]
Took me a while to answer that :)

Anyway, issues and pull requests welcome if you ever find a problem or a new version of a dependency cause trouble.

I have considered doing something about the style of the code but the change would be so big as to literally kill the history.

**Comment by msoos** [comment]
Yeah, no worries, point is that it builds reliably and on modern systems. That's all I need :) Thanks again!
