### ISSUE TITLE
Tighter config.h.in

### ISSUE THREAD

**Issue by SnarkBoojum** [BRiAl/BRiAl#38]
In version 1.2.6, libbrial/include/polybori/config.h.in is provided by autoheader and contains many definitions, most of which are just useless.

The Debian tools detect some of those definitions as potentially clashing with other files named config.h on a system and complain, so I'm going to write a tighter version, with only what's needed.

I'll post my patch here when it will look correct.

**Comment by SnarkBoojum** [comment]
Here it is.
[tighter_config_h.txt](https://github.com/BRiAl/BRiAl/files/4041167/tighter_config_h.txt)

**Comment by kiwifb** [comment]
I thought you would provide a pull request. Never mind, how urgent would you say it is to release this?

**Comment by SnarkBoojum** [comment]
It's not urgent at all. Thanks!
