### ISSUE TITLE
PBORI_HAVE_M4RI, PBORI_HAVE_NTL and bad API

### ISSUE THREAD

**Issue by SnarkBoojum** [BRiAl/BRiAl#40]
I noticed missing symbols on Debian (faugereStepDense in GroebnerStrategy), and set out to find out what the problem was. It turns out there where three of them.

The function is defined in GroebnerStrategy.cc, but protected by #defined PBORI_HAVE_NTL or PBORI_HAVE_M4RI ; but its declaration is unconditional in GroebnerStrategy.h, so that's a problem with the api, and should be fixed. First problem.

And then, I thought perhaps Debian was building without NTL & M4RI -- but when I checked : we do have M4RI. So I tried to find where PBORI_HAVE_M4RI is supposed to be defined : config.h! So it looked like my recent patch was the culprit. Until I checked with the autoheader-generated file : it doesn't have that either! So that makes a second thing to fix, by adding to config.h.in:

>  /* has m4ri */
#undef PBORI_HAVE_M4RI

Second problem.

Finally PBORI_HAVE_NTL is used in a few places, but never actually defined, so either it should be handled in configure.ac, or dropped. Third problem.

Cheers!

**Comment by kiwifb** [comment]
I will likely drop PBORI_HAVE_NTL. It is likely a remnant, ntl is not a dependency of brial and hasn't been for quite a while as far as I remember.

Will the change require bumping LT_CURRENT or LT_REVISION in your opinion.

**Comment by SnarkBoojum** [comment]
Hmmm... I would say no... But it's a good question : I'm unsure...

**Comment by kiwifb** [comment]
Removing PBORI_HAVE_NTL leads to some code simplifications that are not obvious at first glance. I don't think we are changing any API technically, so no bumps. But some code blocks will go.

**Comment by kiwifb** [comment]
I hate the fact that the code can be different formatting style in the same file. Make things harder to follow properly. But standardizing the style would basically destroy the history.

**Comment by kiwifb** [comment]
Because m4ri is a requirement at configure time, I think I will also eliminate all conditionals on PBORI_HAVE_M4RI in the code. I should still add it to `config.h.in`. That will completely get rid of the problems with `faugereStepDense`.

**Comment by kiwifb** [comment]
OK, master should have stuff for all these now. Let me know if your problems are still happening. And don't hesitate to signal any other issue.

**Comment by kiwifb** [comment]
I am preparing 1.2.7 which should have a sdist on github in the next 24 hours. For the record, following libtool guideline I incremented LT_REVISION. You should do that for any code change. I didn't bump it in 1.2.6 because the release only touched the sage python code part of the tarball.

**Comment by kiwifb** [comment]
OK. Closing. Any new stuff will be for a new issue.
