### ISSUE TITLE
brial/general_boolean_polynomial.py:449: SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by SnarkBoojum** [BRiAl/BRiAl#41]
A recent Python 3 change gives this warning

**Comment by SnarkBoojum** [comment]
[python3_warning.txt](https://github.com/BRiAl/BRiAl/files/4057795/python3_warning.txt)

**Comment by kiwifb** [comment]
OK, I will include that this week. You are giving me enough stuff that we may actually have a significant release.

**Comment by kiwifb** [comment]
Done.
