### ISSUE TITLE
[PATCH] Failing test on ia64 and alpha architecture

### ISSUE THREAD

**Issue by SnarkBoojum** [BRiAl/BRiAl#45]
I found the following patch in the Debian packaging ; it dates back to 2013, and I just realized it might never have been forwarded upstream!

**Comment by kiwifb** [comment]
Link?

**Comment by SnarkBoojum** [comment]
[0003-Protect-CErrorInfo-from-invalid-array-access.txt](https://github.com/BRiAl/BRiAl/files/4093708/0003-Protect-CErrorInfo-from-invalid-array-access.txt)

**Comment by SnarkBoojum** [comment]
Eh, I had to first open the issue, then document the report in the patch, and then attach the patch... :-)

**Comment by kiwifb** [comment]
I got it so everything is all right. Wish I had that before tagging the release :(

**Comment by SnarkBoojum** [comment]
No problem, that can wait - it already has since 2013 according to git blame...

**Comment by SnarkBoojum** [comment]
Closing since it's done. I'm glad this patch has been put to rest upstream.

**Comment by kiwifb** [comment]
I have published 1.2.8 which includes this fix amongst other things.

**Comment by SnarkBoojum** [comment]
Yes, I saw. Thanks!
