### ISSUE TITLE
VERSION in polybori/config.h ?

### ISSUE THREAD

**Issue by dimpase** [BRiAl/BRiAl#46]
In Debian (brial 1.2.4) and Fedora (1.2.5) there is a handy macro VERSION, e.g.
```
/* Version number of package */
#define VERSION "1.2.5"
```
But not e.g. in Gentoo. Does it need another way to generate `polybori/config.h` ?

**Comment by kiwifb** [comment]
If there are patches for this in debian and fedora, I'd be happy to apply one. But I don't think that's the case. I think the absence of such version number in `config.h` is a consequence on #38 submitted by a debian dev.
@SnarkBoojum do you think there is something we could do to get `VERSION` back or do you think it is useless or belongs somewhere else?

**Comment by dimpase** [comment]
I left a comment on this here: https://github.com/BRiAl/BRiAl/commit/e32732919f670c0d05b5276b056893485ebd73d9#commitcomment-39661431

So `autoheader` seems to provide a better header.

**Comment by kiwifb** [comment]
I have included some package info in the 1.2.9 release. Let me know if they are enough. I thought of just making a .pc file but then I have other stuff to do. Feel free to send me a PR for that if you want to.
