### ISSUE TITLE
Update ax_boost_base.m4

### ISSUE THREAD

**Issue by jengelh** [BRiAl/BRiAl#49]
ax_boost_base.m4 as shipped by brial does not recognize riscv64. As a result, it looks in the wrong directory and cannot find boost_test_framework.so. Please update ax_boost_base.m4 with a new version from the autoconf-archive.

**Comment by kiwifb** [comment]
Thanks for the report. I have pushed some updates on master. Once I have some good test report I will make a new maintenance release.

**Comment by kiwifb** [comment]
1.2.9 with updated macros is out. I am closing this ticket but do let me know if there are further issues.
